// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/menger/menger.proto

package wm_sx_svc_menger

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Menger service

type MengerService interface {
	Login(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*LoginResponse, error)
}

type mengerService struct {
	c    client.Client
	name string
}

func NewMengerService(name string, c client.Client) MengerService {
	return &mengerService{
		c:    c,
		name: name,
	}
}

func (c *mengerService) Login(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*LoginResponse, error) {
	req := c.c.NewRequest(c.name, "Menger.Login", in)
	out := new(LoginResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Menger service

type MengerHandler interface {
	Login(context.Context, *LoginRequest, *LoginResponse) error
}

func RegisterMengerHandler(s server.Server, hdlr MengerHandler, opts ...server.HandlerOption) error {
	type menger interface {
		Login(ctx context.Context, in *LoginRequest, out *LoginResponse) error
	}
	type Menger struct {
		menger
	}
	h := &mengerHandler{hdlr}
	return s.Handle(s.NewHandler(&Menger{h}, opts...))
}

type mengerHandler struct {
	MengerHandler
}

func (h *mengerHandler) Login(ctx context.Context, in *LoginRequest, out *LoginResponse) error {
	return h.MengerHandler.Login(ctx, in, out)
}
